CREATE TABLE IF NOT EXISTS users
(
    id    int generated by default as identity not null,
    name  varchar(50)                          not null,
    email varchar(50),
    constraint pk_user primary key (id),
    constraint user_email unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          int generated by default as identity not null,
    owner_id    int                                  not null,
    name        varchar(50),
    description varchar(200),
    available   boolean,
    constraint pk_item primary key (id),
    constraint fk_item foreign key (owner_id) references users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id            int generated by default as identity not null,
    booker_id     int                                  not null,
    item_id       int                                  not null,
    start_booking timestamp with time zone             not null,
    end_booking   timestamp with time zone             not null,
    status        varchar                              not null,
    constraint pk_booking primary key (id),
    constraint fk_booker foreign key (booker_id) references users (id),
    constraint fk_booking_items foreign key (item_id) references items (id)
);

CREATE TABLE if not exists comments
(
    id           int generated by default as identity not null,
    item_id      int                                  not null,
    text         varchar(300)                         not null,
    author_name  varchar(100)                         not null,
    created_time timestamp                            not null,
    constraint pk_comments primary key (id),
    constraint fk_items foreign key (item_id) references items (id)
);